permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: kramdown
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
   ,"html_toc"
  ]
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: ":num"
baseurl: ""

title: ""
email: "wangbangkun@yeah.net"
description: ""
github_username:  "wangbangkun"


url: "http://wangbangkun.github.io"
imgrepo: "http://wangbangkun.github.io/static/img/posts"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img/posts"

